### ISSUE TITLE
NSFW Project

### ISSUE THREAD

**Issue by dreamsoftech** [thehamkercat/WilliamButcherBot#125]
Hi @TheHamkerCat 
I am a CTO at WALTB and we are building video chatting application.
In our application, we need to implement NSFW processing and I need your help.
I tried yahoo NSFW engine and it's a little slow than we need.
We need to process image within 30 ~ 50 ms but yahoo engine takes 70 ~ 80ms.
So I tried to find alternative solution and I am reaching out to you.
Can we schedule a call and discuss the project?
My email is andrew@waltb.co.
My github handle is dreamsoftech
My skype is dreamsoftech88

Looking forward to your reply.
Thanks,
Andrew

**Comment by TheHamkerCat** [comment]
> Hi @TheHamkerCat I am a CTO at WALTB and we are building video chatting application. In our application, we need to implement NSFW processing and I need your help. I tried yahoo NSFW engine and it's a little slow than we need. We need to process image within 30 ~ 50 ms but yahoo engine takes 70 ~ 80ms. So I tried to find alternative solution and I am reaching out to you. Can we schedule a call and discuss the project? My email is [andrew@waltb.co](mailto:andrew@waltb.co). My github handle is dreamsoftech My skype is dreamsoftech88
> 
> Looking forward to your reply. Thanks, Andrew
![image](https://user-images.githubusercontent.com/58004714/137430020-deb706b2-2f26-4819-b76d-8c9c9739ec55.png)

Spam
