### ISSUE TITLE
About future plan

### ISSUE THREAD

**Issue by NPriyo** [thehamkercat/WilliamButcherBot#194]
Any future plan to support deployment on GitHub workflow?

**Comment by TheHamkerCat** [comment]
Don't bite the hand that feeds you. I don't support anyone trying to abuse a platform

**Comment by sumeetweb** [comment]
Not possible imo. Github Actions have a strict timeout of 360 minutes / 6 hours and run only for 2000 minutes monthly for personal private repos. 

You can use actions to deploy onto other cloud platforms as usual.

**Comment by NPriyo** [comment]
> Not possible imo. Github Actions have a strict timeout of 360 minutes / 6 hours and run only for 2000 minutes monthly for personal private repos.
> 
> You can use actions to deploy onto other cloud platforms as usual.

Thanks for the info!
