### ISSUE TITLE
bug / issue with button callback query answering

### ISSUE THREAD

**Issue by SpEcHiDe** [thehamkercat/WilliamButcherBot#72]
https://github.com/TheHamkerCat/WilliamButcherBot/blob/dev/wbb/modules/spam.py#L110
https://github.com/TheHamkerCat/WilliamButcherBot/blob/dev/wbb/modules/admin.py#L57

get_chat_member will raise UserNotParticipant if any user not a member of the group tries to click on the buttons. which would result in a just a spinning circle, and eventually would result in [a notification from @BotFather](https://telegra.ph/file/5760f4f15383d0ba06444.jpg), saying **Too few answers to callback queries**.

**Comment by TheHamkerCat** [comment]
Fixed in last commit, thanks.
