### ISSUE TITLE
Heroku deployment issue

### ISSUE THREAD

**Issue by thedevakrishna** [thehamkercat/WilliamButcherBot#95]
when deploying heroku error "an unexpected error caused the job to fail"  
https://user-images.githubusercontent.com/78889898/126060337-5f1645aa-99d8-416a-9861-c911c2f505d7.png)

**Comment by TheHamkerCat** [comment]
Logs or GTFO

**Comment by thedevakrishna** [comment]
not able to deploy, so no logs

**Comment by TheHamkerCat** [comment]
Heroku shows error logs during deployment

**Comment by thedevakrishna** [comment]
![image](https://user-images.githubusercontent.com/78889898/126258014-c604d831-8522-4699-a243-b4cedc75c7ba.png)

**Comment by TheHamkerCat** [comment]
Sorry, but i can't do anything without seeing what's the error, you probably wrote something wrong in the config vars, Can you show me what did you actually filled there? hide the half of it.

**Comment by TheHamkerCat** [comment]
Fixed perhaps
